FOOD_CATEGORY_MAP = {
    "Fruits":                          "Fruits, Vegetables, Salads",
    "Green Leafy Vegetables":          "Fruits, Vegetables, Salads",
    "Other Vegetables":                "Fruits, Vegetables, Salads",
    "Animal Meat":                     "Meat, MAP",
    "Poultry":                         "Meat, MAP",
    "Marine Fish":                     "Fresh meat, MAP",
    "Fresh Water Fish and Shellfish":  "Fresh meat, MAP",
    "Marine Shellfish":                "Fresh meat, MAP",
    "Marine Mollusks":                 "Fresh meat, MAP",
    "Cereals and Millets":             "Bakery products",
    "Grain Legumes":                   "Peanuts",
    "Nuts and Oil Seeds":              "Peanuts",
    "Milk and Milk Products":          "Cheese",
    "Condiments and Spices":           "Instant coffee",
    "Mushrooms":                       "Meat, MAP",
    "Egg and Egg Products":            "Bakery products",
    "Sugars":                          "Bakery products",
    "Roots and Tubers":                "Fruits, Vegetables, Salads",
    "Edible Oils and Fats":            "Edible Oils and Fats",
    "Miscellaneous Foods":             None,
}
